/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avropesquisadores;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Pesquisador extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6008367016929224191L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Pesquisador\",\"namespace\":\"avropesquisadores\",\"fields\":[{\"name\":\"colaboradores\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence colaboradores;
  @Deprecated public java.lang.CharSequence id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Pesquisador() {}

  /**
   * All-args constructor.
   * @param colaboradores The new value for colaboradores
   * @param id The new value for id
   */
  public Pesquisador(java.lang.CharSequence colaboradores, java.lang.CharSequence id) {
    this.colaboradores = colaboradores;
    this.id = id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return colaboradores;
    case 1: return id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: colaboradores = (java.lang.CharSequence)value$; break;
    case 1: id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'colaboradores' field.
   * @return The value of the 'colaboradores' field.
   */
  public java.lang.CharSequence getColaboradores() {
    return colaboradores;
  }

  /**
   * Sets the value of the 'colaboradores' field.
   * @param value the value to set.
   */
  public void setColaboradores(java.lang.CharSequence value) {
    this.colaboradores = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Creates a new Pesquisador RecordBuilder.
   * @return A new Pesquisador RecordBuilder
   */
  public static avropesquisadores.Pesquisador.Builder newBuilder() {
    return new avropesquisadores.Pesquisador.Builder();
  }

  /**
   * Creates a new Pesquisador RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Pesquisador RecordBuilder
   */
  public static avropesquisadores.Pesquisador.Builder newBuilder(avropesquisadores.Pesquisador.Builder other) {
    return new avropesquisadores.Pesquisador.Builder(other);
  }

  /**
   * Creates a new Pesquisador RecordBuilder by copying an existing Pesquisador instance.
   * @param other The existing instance to copy.
   * @return A new Pesquisador RecordBuilder
   */
  public static avropesquisadores.Pesquisador.Builder newBuilder(avropesquisadores.Pesquisador other) {
    return new avropesquisadores.Pesquisador.Builder(other);
  }

  /**
   * RecordBuilder for Pesquisador instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Pesquisador>
    implements org.apache.avro.data.RecordBuilder<Pesquisador> {

    private java.lang.CharSequence colaboradores;
    private java.lang.CharSequence id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avropesquisadores.Pesquisador.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.colaboradores)) {
        this.colaboradores = data().deepCopy(fields()[0].schema(), other.colaboradores);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Pesquisador instance
     * @param other The existing instance to copy.
     */
    private Builder(avropesquisadores.Pesquisador other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.colaboradores)) {
        this.colaboradores = data().deepCopy(fields()[0].schema(), other.colaboradores);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'colaboradores' field.
      * @return The value.
      */
    public java.lang.CharSequence getColaboradores() {
      return colaboradores;
    }

    /**
      * Sets the value of the 'colaboradores' field.
      * @param value The value of 'colaboradores'.
      * @return This builder.
      */
    public avropesquisadores.Pesquisador.Builder setColaboradores(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.colaboradores = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'colaboradores' field has been set.
      * @return True if the 'colaboradores' field has been set, false otherwise.
      */
    public boolean hasColaboradores() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'colaboradores' field.
      * @return This builder.
      */
    public avropesquisadores.Pesquisador.Builder clearColaboradores() {
      colaboradores = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public avropesquisadores.Pesquisador.Builder setId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public avropesquisadores.Pesquisador.Builder clearId() {
      id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Pesquisador build() {
      try {
        Pesquisador record = new Pesquisador();
        record.colaboradores = fieldSetFlags()[0] ? this.colaboradores : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
